-- HSG Runner - Supabase Database Schema
-- Copy and paste this into the Supabase SQL Editor

-- 1. Create rooms table
CREATE TABLE IF NOT EXISTS rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  host_id TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('PUBLIC', 'PRIVATE')),
  status TEXT NOT NULL DEFAULT 'LOBBY' CHECK (status IN ('LOBBY', 'PLAYING', 'FINISHED')),
  player_count INTEGER DEFAULT 1,
  short_id TEXT UNIQUE NOT NULL,
  start_time TIMESTAMPTZ,
  map_id INTEGER DEFAULT 1
);

-- 2. Create players table
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  is_ready BOOLEAN DEFAULT false,
  last_seen TIMESTAMPTZ DEFAULT now(),
  distance INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0,
  is_dead BOOLEAN DEFAULT false,
  is_finished BOOLEAN DEFAULT false,
  lane INTEGER DEFAULT 0,
  y FLOAT DEFAULT 0,
  z FLOAT DEFAULT 0,
  UNIQUE(room_id, user_id)
);

-- 3. Create global leaderboard table (Optional but recommended)
CREATE TABLE IF NOT EXISTS global_leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  distance INTEGER NOT NULL
);

-- 4. Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  avatar_url TEXT,
  points INTEGER DEFAULT 0,
  current_level INTEGER DEFAULT 1,
  current_map INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  item_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  purchased_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, item_id)
);

-- 6. Enable Realtime for these tables
-- Note: You might need to do this manually in the Supabase Dashboard under Database -> Replication
-- but these commands attempt to do it via SQL.
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE players;
ALTER PUBLICATION supabase_realtime ADD TABLE global_leaderboard;
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE inventory;

-- 7. Enable Row Level Security (RLS)
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE global_leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

-- 8. Create permissive policies (Allow anyone to read/write for the game)
-- 8. Create permissive policies (Allow anyone to read/write for the game)
-- In a production app, you would restrict these more.
DROP POLICY IF EXISTS "Public Rooms Access" ON rooms;
CREATE POLICY "Public Rooms Access" ON rooms FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Players Access" ON players;
CREATE POLICY "Public Players Access" ON players FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Leaderboard Access" ON global_leaderboard;
CREATE POLICY "Public Leaderboard Access" ON global_leaderboard FOR ALL USING (true) WITH CHECK (true);

-- Profiles policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON profiles;
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON profiles;
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Inventory policies
DROP POLICY IF EXISTS "Public inventory is viewable by everyone." ON inventory;
CREATE POLICY "Public inventory is viewable by everyone." ON inventory FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own inventory." ON inventory;
CREATE POLICY "Users can insert their own inventory." ON inventory FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own inventory." ON inventory;
CREATE POLICY "Users can update own inventory." ON inventory FOR UPDATE USING (auth.uid() = user_id);

-- 9. Function to clean up inactive players/rooms (Optional)
-- You can run this as a cron job or manually if needed.
-- DELETE FROM players WHERE last_seen < now() - interval '1 minute';
-- DELETE FROM rooms WHERE id NOT IN (SELECT DISTINCT room_id FROM players);

-- ============================================================
-- CITADEL RUNNER — VERIFIED SCORES
-- ------------------------------------------------------------
-- The runner is an endless game, so there is no single "level end"
-- to hang a score off. Every death is submitted to /api/runner-score,
-- which checks the claim against the runner's own physics and stamps
-- it with an HMAC receipt. Only rows written here (or accepted in
-- memory when this table is absent) can appear on a share card.
--
-- device_id is an opaque random id kept in the player's localStorage.
-- No IP, email or personal data is stored.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.runner_scores (
  id          BIGSERIAL PRIMARY KEY,
  device_id   TEXT        NOT NULL,
  score       BIGINT      NOT NULL DEFAULT 0,
  distance    INTEGER     NOT NULL DEFAULT 0,
  gems        INTEGER     NOT NULL DEFAULT 0,
  letters     INTEGER     NOT NULL DEFAULT 0,
  tiers       INTEGER     NOT NULL DEFAULT 1,
  seconds     INTEGER     NOT NULL DEFAULT 0,
  receipt     TEXT        NOT NULL DEFAULT '',
  verified    BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per device keeps the ledger small and idempotent.
CREATE UNIQUE INDEX IF NOT EXISTS runner_scores_device_key
  ON public.runner_scores (device_id);

CREATE INDEX IF NOT EXISTS runner_scores_best_idx
  ON public.runner_scores (score DESC);

-- Only the endpoint's service key may write; everyone else reads nothing.
ALTER TABLE public.runner_scores ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.runner_scores FROM anon, authenticated;